p = input("Enter your name :")
q = input("Enter your branch :")
r = input("Enter your gender :")
s = input("Enter your college :")
t = int(input("Enter your age :"))
print("Name:",p)
print("Branch:",q)
print("Gender:",r)
print("College:",s)
print("Age:",t)
