p = input("Enter your name :")
q = input("enter your branch :")
r = input("enter your gender :")
s = input("enter your college :")
t = int(input("ENter your age :"))
print("Name:",p)
print("Branch:",q)
print("Gender:",r)
print("College:",s)
print("Age:",t)
