x=int(input("enter the scores scored by first player on 60 balls"))
y=int(input("enter the scores scored by second player on 60 balls"))
z=int(input("enter the scores scored by third player on 60 balls"))
srate1=float(x*100/60)
srate2=float(y*100/60)
srate3=float(z*100/60)
print("strike rate of the  frist players is",srate1)
print("strike rate of the  second players is",srate2)
print("strike rate of the third players is",srate3)
print("scores of the player if players played 60 more balls")
print("scores by frist players are",x*2)
print("scores by second players are",y*2)
print("scores by third players are",z*2)
print("no of sixes in first player",int(x/6))
print("no of sixes in second player",int(y/6))
print("no of sixes in third player",int(z/6))

